# This file was generated by GoReleaser. DO NOT EDIT.
cask "as2inspect" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "833d6c10b81063fabfffe9753eb7bf1ce10333687fb34595b085f455698082e3"
      url "https://github.com/certcutover/as2inspect/releases/download/v#{version}/as2inspect_darwin_amd64"
      binary "as2inspect_darwin_amd64", target: "as2inspect"
    end
    on_arm do
      sha256 "1499e81b54645342f7d8ce747d7495f6d7eb5c006848f2273f613fc27d3b898a"
      url "https://github.com/certcutover/as2inspect/releases/download/v#{version}/as2inspect_darwin_arm64"
      binary "as2inspect_darwin_arm64", target: "as2inspect"
    end
  end

  on_linux do
    on_intel do
      sha256 "4ad89096b79eec92078632b84e0a64c68254e49fbc470cb2604319ec4f6a62c1"
      url "https://github.com/certcutover/as2inspect/releases/download/v#{version}/as2inspect_linux_amd64"
      binary "as2inspect_linux_amd64", target: "as2inspect"
    end
    on_arm do
      sha256 "e7f23d132de4f30f73a6e82aecd9b9e3d94e208da805c09c7876e216b51618de"
      url "https://github.com/certcutover/as2inspect/releases/download/v#{version}/as2inspect_linux_arm64"
      binary "as2inspect_linux_arm64", target: "as2inspect"
    end
  end

  name "as2inspect"
  desc "Inspect AS2 & X.509 certificates: role, expiry, fingerprint"
  homepage "https://certcutover.com"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
