# This file was generated by GoReleaser. DO NOT EDIT.
cask "as2inspect" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "fa975f5972e8fc14b292fcbae6cab236ea247874a598c50f3811ff6c6356cdfb"
      url "https://github.com/certcutover/as2inspect/releases/download/v#{version}/as2inspect_darwin_amd64"
      binary "as2inspect_darwin_amd64", target: "as2inspect"
    end
    on_arm do
      sha256 "206f799a5695dc04b4beb682a3ac6fcdc6a2d6a1e1f634827b0d7a3bf5e1d6c8"
      url "https://github.com/certcutover/as2inspect/releases/download/v#{version}/as2inspect_darwin_arm64"
      binary "as2inspect_darwin_arm64", target: "as2inspect"
    end
  end

  on_linux do
    on_intel do
      sha256 "98db35b97eaf57f41037b0c73bd8aa3b85476a2ab47579457252f84999979257"
      url "https://github.com/certcutover/as2inspect/releases/download/v#{version}/as2inspect_linux_amd64"
      binary "as2inspect_linux_amd64", target: "as2inspect"
    end
    on_arm do
      sha256 "e032b5409a8bf62aeb26763264b7d48fd71b45cc096bfbae30215678838443d5"
      url "https://github.com/certcutover/as2inspect/releases/download/v#{version}/as2inspect_linux_arm64"
      binary "as2inspect_linux_arm64", target: "as2inspect"
    end
  end

  name "as2inspect"
  desc "Inspect AS2 & X.509 certificates: role, expiry, fingerprint"
  homepage "https://certcutover.com"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/as2inspect"]
    end
  end

  # No zap stanza required

end
