# This file was generated by GoReleaser. DO NOT EDIT.
cask "as2inspect" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "0a70193d3e374033236f6327675a92573362c04894ec0f75e1190a258787e5e4"
      url "https://github.com/yanzay/as2inspect/releases/download/v#{version}/as2inspect_darwin_amd64"
      binary "as2inspect_darwin_amd64", target: "as2inspect"
    end
    on_arm do
      sha256 "283108e67b0456b7d2537255c35d0cbf2d1241c9c1542c13f9f03477e59a470a"
      url "https://github.com/yanzay/as2inspect/releases/download/v#{version}/as2inspect_darwin_arm64"
      binary "as2inspect_darwin_arm64", target: "as2inspect"
    end
  end

  on_linux do
    on_intel do
      sha256 "7971a239678f0cefd5017429f572a4f2f57444b172a49057d9aedc3f1c13e43f"
      url "https://github.com/yanzay/as2inspect/releases/download/v#{version}/as2inspect_linux_amd64"
      binary "as2inspect_linux_amd64", target: "as2inspect"
    end
    on_arm do
      sha256 "f782d93cbc2752bae9cbe1c2ae094bbaef9243b2104ddb4b3f983c20a90c307c"
      url "https://github.com/yanzay/as2inspect/releases/download/v#{version}/as2inspect_linux_arm64"
      binary "as2inspect_linux_arm64", target: "as2inspect"
    end
  end

  name "as2inspect"
  desc "Inspect AS2 & X.509 certificates: role, expiry, fingerprint"
  homepage "https://certcutover.com"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
